openGemini/opengemini-client-go

- go.mod
chore: modify go.mod module to make sure the project could be imported
> chore: modify go.mod module to make sure the project could be imported

- opengemini/client.go
- opengemini/client_impl.go
- opengemini/client_ping_test.go
chore: rename addressList to addresses
> chore: rename addressList to addresses

- opengemini/http.go
- opengemini/ping_test.go
> fix: add check to avoid illegal index make out of bounds

- opengemini/client.go
- opengemini/http.go
- opengemini/query.go
> feat: support query method

- .github/workflows/line_lint.yml
- opengemini/client.go
- opengemini/database.go
- opengemini/database_test.go
- opengemini/http.go
- opengemini/query.go
- opengemini/query_result.go
- opengemini/retention_policy.go
- opengemini/retention_policy_test.go
API for managing databases and retention policies
> feat: API for managing databases and retention policies

- opengemini/client.go
- opengemini/client_impl.go
- opengemini/write.go
feat: support write points in batches with callback2(with 2 times batch channel buffer)
> feat: support write points in batches with callback

- opengemini/client.go
- opengemini/database.go
- opengemini/database_test.go
> refactor: rename method ShowDatabase to ShowDatabases

- opengemini/point.go
- opengemini/write_test.go
> chore: add integer's symbol in parseFields method to enhance performance

- opengemini/database.go
- opengemini/database_test.go
- opengemini/retention_policy.go
chore: auto escape the database name
> chore: auto escape the database name

- README.md
Modify the code indentation in the README file
> chore: Modify the code indentation in the README file

- opengemini/ping.go
- opengemini/query.go
- opengemini/write.go
put the status judge in the query
> fix: standardize the error handling in query.go, write.go, and ping.go 

- opengemini/point.go
- opengemini/query.go
- opengemini/query_test.go
> feat: enable query with precision

- README.md
- README_CN.md
([fix issue74]
(https://github.com/openGemini/opengemini-client-go/issues/74))
> docs: write single point with context in readme

- opengemini/client.go
- opengemini/write.go
- opengemini/write_test.go
> feat: support write data into special retention policy

- opengemini/random_util.go
- opengemini/random_util_test.go
- opengemini/write_test.go
> chore: test file format

- opengemini/ping.go
> fix: http body no close #92

- opengemini/measurement.go
- opengemini/query.go
> perf: minimize assertion calls and reduce overhead

- opengemini/servers_check.go
- opengemini/servers_check_test.go
> chore: error uses the common naming format

- opengemini/client_impl.go
> feat: support ipv6 address

- README.md
- README_CN.md
> docs: add client design doc link in README

- opengemini/http.go
- opengemini/ping.go
- opengemini/servers_check.go
> fix: ping with context

- opengemini/client.go
> chore: add detailed description for BatchSize

- README.md
- README_CN.md
- examples/example/example.go
- opengemini/point.go
- opengemini/point_test.go
- opengemini/query_test.go
- opengemini/write_test.go
> chore: delete redundant setters

- opengemini/client.go
- opengemini/write.go
> chore: add CallbackDummy as empty WriteCallback

- go.mod
> chore: update go build version

- README.md
- README_CN.md
- examples/example/example.go
- opengemini/client.go
- opengemini/http.go
- opengemini/write.go
- opengemini/write_test.go
Provide ctx parameters for batch operation.
> feat: write batch support ctx param

- README.md
- README_CN.md
- examples/example/example.go
> docs: remove dot import

- opengemini/client.go
- opengemini/measurement.go
feat: support drop measurement method
> feat: support drop measurement method

- .github/workflows/go_ci_lint.yml
- examples/multiple-clients/main.go
- opengemini/database.go
- opengemini/error.go
- opengemini/measurement.go
- opengemini/retention_policy.go
- opengemini/write.go
- opengemini/write_test.go
> refactor: extract common error checking logic into a shared function

- opengemini/write.go
- opengemini/write_test.go
> feat: return directly when write empty point list

- opengemini/point.go
- opengemini/point_test.go
> fix: modify encoder according to line protocol.

- opengemini/client.go
- opengemini/client_impl.go
> refactor: remove config.TlsEnabled

- .github/workflows/pr-title-lint.yml
Add PR title lint CI to check if the submitted PR title does not meet the requirements
> ci: pr title lint

- examples/example/example.go
- go.mod
- opengemini/client.go
- opengemini/query.go
- opengemini/query_test.go
- opengemini/write.go
The server already supports ZSTD encoding; the client should adapt to this.
> feat(perf): enable config zstd

- go.mod
- go.sum
- opengemini/client.go
- opengemini/query.go
- opengemini/query_test.go
> feat(compress): add snappy

- examples/example/example.go
- opengemini/measurement_test.go
- opengemini/point.go
- opengemini/point_test.go
- opengemini/query_test.go
- opengemini/write_test.go
remove `Point` struct Time field.
> refactor: remove point time field

- opengemini/error.go
- opengemini/http.go
- opengemini/servers_check.go
- opengemini/servers_check_test.go
return random http server url when all server down
> chore: return random http server url when all server down

- README.md
- README_CN.md
> docs: fix the config address setting usage

- .typos.toml
- examples/example/example.go
- go.mod
- go.sum
- opengemini/database.go
- opengemini/query.go
- opengemini/query_test.go
client to support the bound parameter mode.
fixed: #220
> feat: bound parameter mode

- README.md
- README_CN.md
Add the CNCF Best Practices badge for the project, associated with bestpractices.dev ID 11013.
> docs: add CNCF best practice badge
